title: Leaf Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-hacker

# for a clean URL
permalink: :slug

social:
  github: C4sp3N

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
